name: Build LKM for KernelSU
on:
  workflow_call:
    inputs:
      expected_pr_build_size:
        description: 'Second expected signature size (for PR builds)'
        required: false
        default: ''
        type: string
      expected_pr_build_hash:
        description: 'Second expected signature hash (for PR builds)'
        required: false
        default: ''
        type: string
  workflow_dispatch:
jobs:
  build-lkm:
    strategy:
      fail-fast: false
      matrix:
        kmi:
          - android15-6.6
        arch:
          - arm64
          - x86_64
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
      arch: ${{ matrix.arch }}
      expected_pr_build_size: ${{ inputs.expected_pr_build_size || '' }}
      expected_pr_build_hash: ${{ inputs.expected_pr_build_hash || '' }}
